// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: testmodule.proto

package testmodule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TheTestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsTest bool   `protobuf:"varint,1,opt,name=isTest,proto3" json:"isTest,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TheTestReq) Reset() {
	*x = TheTestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testmodule_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TheTestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TheTestReq) ProtoMessage() {}

func (x *TheTestReq) ProtoReflect() protoreflect.Message {
	mi := &file_testmodule_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TheTestReq.ProtoReflect.Descriptor instead.
func (*TheTestReq) Descriptor() ([]byte, []int) {
	return file_testmodule_proto_rawDescGZIP(), []int{0}
}

func (x *TheTestReq) GetIsTest() bool {
	if x != nil {
		return x.IsTest
	}
	return false
}

func (x *TheTestReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TheTestRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res *TheTestRes_Res `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *TheTestRes) Reset() {
	*x = TheTestRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testmodule_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TheTestRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TheTestRes) ProtoMessage() {}

func (x *TheTestRes) ProtoReflect() protoreflect.Message {
	mi := &file_testmodule_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TheTestRes.ProtoReflect.Descriptor instead.
func (*TheTestRes) Descriptor() ([]byte, []int) {
	return file_testmodule_proto_rawDescGZIP(), []int{1}
}

func (x *TheTestRes) GetRes() *TheTestRes_Res {
	if x != nil {
		return x.Res
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testmodule_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_testmodule_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_testmodule_proto_rawDescGZIP(), []int{2}
}

type SpamMeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spam string `protobuf:"bytes,1,opt,name=spam,proto3" json:"spam,omitempty"`
}

func (x *SpamMeRes) Reset() {
	*x = SpamMeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testmodule_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpamMeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpamMeRes) ProtoMessage() {}

func (x *SpamMeRes) ProtoReflect() protoreflect.Message {
	mi := &file_testmodule_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpamMeRes.ProtoReflect.Descriptor instead.
func (*SpamMeRes) Descriptor() ([]byte, []int) {
	return file_testmodule_proto_rawDescGZIP(), []int{3}
}

func (x *SpamMeRes) GetSpam() string {
	if x != nil {
		return x.Spam
	}
	return ""
}

type TheTestRes_Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response   string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Statuscode int64  `protobuf:"varint,2,opt,name=statuscode,proto3" json:"statuscode,omitempty"`
}

func (x *TheTestRes_Res) Reset() {
	*x = TheTestRes_Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testmodule_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TheTestRes_Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TheTestRes_Res) ProtoMessage() {}

func (x *TheTestRes_Res) ProtoReflect() protoreflect.Message {
	mi := &file_testmodule_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TheTestRes_Res.ProtoReflect.Descriptor instead.
func (*TheTestRes_Res) Descriptor() ([]byte, []int) {
	return file_testmodule_proto_rawDescGZIP(), []int{1, 0}
}

func (x *TheTestRes_Res) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *TheTestRes_Res) GetStatuscode() int64 {
	if x != nil {
		return x.Statuscode
	}
	return 0
}

var File_testmodule_proto protoreflect.FileDescriptor

var file_testmodule_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x65, 0x73, 0x74, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x36, 0x0a, 0x0a, 0x54, 0x68, 0x65, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x54, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x69, 0x73, 0x54, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x72, 0x0a, 0x0a, 0x54, 0x68,
	0x65, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x68, 0x65, 0x54, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x52, 0x03, 0x72, 0x65, 0x73, 0x1a, 0x41, 0x0a, 0x03, 0x52,
	0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x1f, 0x0a, 0x09, 0x53, 0x70, 0x61, 0x6d, 0x4d,
	0x65, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x70, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x70, 0x61, 0x6d, 0x32, 0x52, 0x0a, 0x0d, 0x74, 0x65, 0x73, 0x74,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x76, 0x63, 0x12, 0x23, 0x0a, 0x07, 0x54, 0x68, 0x65,
	0x54, 0x65, 0x73, 0x74, 0x12, 0x0b, 0x2e, 0x54, 0x68, 0x65, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x0b, 0x2e, 0x54, 0x68, 0x65, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x1c,
	0x0a, 0x06, 0x53, 0x70, 0x61, 0x6d, 0x4d, 0x65, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x0a, 0x2e, 0x53, 0x70, 0x61, 0x6d, 0x4d, 0x65, 0x52, 0x65, 0x73, 0x42, 0x0f, 0x5a, 0x0d,
	0x2e, 0x2f, 0x3b, 0x74, 0x65, 0x73, 0x74, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testmodule_proto_rawDescOnce sync.Once
	file_testmodule_proto_rawDescData = file_testmodule_proto_rawDesc
)

func file_testmodule_proto_rawDescGZIP() []byte {
	file_testmodule_proto_rawDescOnce.Do(func() {
		file_testmodule_proto_rawDescData = protoimpl.X.CompressGZIP(file_testmodule_proto_rawDescData)
	})
	return file_testmodule_proto_rawDescData
}

var file_testmodule_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_testmodule_proto_goTypes = []interface{}{
	(*TheTestReq)(nil),     // 0: TheTestReq
	(*TheTestRes)(nil),     // 1: TheTestRes
	(*Empty)(nil),          // 2: Empty
	(*SpamMeRes)(nil),      // 3: SpamMeRes
	(*TheTestRes_Res)(nil), // 4: TheTestRes.Res
}
var file_testmodule_proto_depIdxs = []int32{
	4, // 0: TheTestRes.res:type_name -> TheTestRes.Res
	0, // 1: testmoduleSvc.TheTest:input_type -> TheTestReq
	2, // 2: testmoduleSvc.SpamMe:input_type -> Empty
	1, // 3: testmoduleSvc.TheTest:output_type -> TheTestRes
	3, // 4: testmoduleSvc.SpamMe:output_type -> SpamMeRes
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_testmodule_proto_init() }
func file_testmodule_proto_init() {
	if File_testmodule_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testmodule_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TheTestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testmodule_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TheTestRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testmodule_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testmodule_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpamMeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testmodule_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TheTestRes_Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testmodule_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testmodule_proto_goTypes,
		DependencyIndexes: file_testmodule_proto_depIdxs,
		MessageInfos:      file_testmodule_proto_msgTypes,
	}.Build()
	File_testmodule_proto = out.File
	file_testmodule_proto_rawDesc = nil
	file_testmodule_proto_goTypes = nil
	file_testmodule_proto_depIdxs = nil
}
